import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.scss';
import Script from 'next/script';

const inter = Inter({ subsets: ['cyrillic-ext'], weight: '400' });

export const metadata: Metadata = {
	title: 'MateMatik',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
	params,
}: {
	params: { lang: string };
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
